### ISSUE TITLE
pow(x) doesn't seems to be working

### ISSUE THREAD

**Issue by Kikillervortlex** [stur86/gd-complex#1]
The code:
	var a = Complex.new(2,0)
	a = a.pow(2)
	print(a.real)
Ouputs :
2

The issue seems to be in the pow() function, with real and I think also with complex numbers

**Comment by higgs-bosoff** [comment]
Thanks for notifying this, fixed in the latest commit that also ports to Godot 4!

Please refer to this fork for the latest changes: https://github.com/higgs-bosoff/gd-complex

**Comment by stur86** [comment]
Solved.
